name: Devops Github CI

on:
  push:
    branches:
      - main

jobs:
  devops:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build Maven Project
      run: mvn clean install

    - name: Build Docker Image
      run: docker build -t e-commercewebsite .